### ISSUE TITLE
Crossing 100 VSIs in a region fails

### ISSUE THREAD

**Issue by michandrz-co** [jonghall/ibmcloud_vpc_ansible_dynamic_inventory#7]
Crossing 100 VSIs fails due to an error in the API. Working with support as long as you tag generation and version it will work.

`
    instances = []
    start = 0
    limit = 100
    url = args.iaas_endpoint + '/v1/instances/' + args.apiversion + "&limit=" + str(limit)

    while True:
        try:
            resp = requests.get(url, headers=args.iamtoken, timeout=30)
            resp.raise_for_status()
        except requests.exceptions.ConnectionError as errc:
            print("Error Connecting:", errc)
            quit()
        except requests.exceptions.Timeout as errt:
            print("Timeout Error:", errt)
            quit()
        except requests.exceptions.HTTPError as errb:
            unknownapierror(resp)

        if resp.status_code == 200:
            result = json.loads(resp.content)
            #total_count = result["total_count"]
            instances = instances + result["instances"]
            if "next" in result:
                url=result["next"]["href"] + '&' + args.apiversion[1:]
                continue
            else:
                break
    return instances
`

**Comment by jonghall** [comment]
Thank you.  i will take a look and incorporate.
